server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: LIU18959297292
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderService # 服务名称，在euraka中展示
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848 # nacos服务地址
#      discovery:
#        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
#        ephemeral: false # 是否是临时实例
#mybatis:
#  type-aliases-package: wo1261931780.orderService.user.pojo
#  configuration:
#    map-underscore-to-camel-case: true
#logging:
#  level:
#    wo1261931780: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#========================================================
#要将服务注册到eureka上，需要在application.yml中添加以下内容：
#注册之前，需要在pom中引入客户端依赖
eureka:
  client:
    service-url: # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
#========================================================
#注意这里是order服务中配置user的调用规则
userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients: # 指定饥饿加载的服务名称
#      - userService
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
